"""`repolens featuretrace propose`: draft FeatureTrace markers from the evidence graph.

    repolens featuretrace propose              write a proposal under .repolens/featuretrace-proposal
    repolens featuretrace propose --jsdoc      also draft fact-only JSDoc for route handlers and data access
    repolens featuretrace propose --function-lens  also draft stable, comment-only function ids
    repolens featuretrace propose --owners     also draft canonical_owners.draft.yaml (never written into the tree)
    repolens featuretrace propose --apply      write the saved, reviewed proposal into the repository

A marker records what a person decided a feature is. This command only drafts one from
static evidence: the route, call and store edges that `impact.features` groups by route
segment. Every role ends in "(draft)" and every tag is a route segment until someone renames
it (`--tag orders=order-management`). Each draft is checked with the audit's own rules and
any issue it predicts is listed in proposal.json (`audit_issues`); passing the audit says the
references are well formed, not that the declared flow is what the feature does.

Drafting writes only to the proposal directory, and refuses to replace a file there that it
did not write. `--apply` does not draft again: it writes the proposal.json saved by the
drafting run, whose patch you reviewed. It refuses to run when there is no saved proposal,
it was drafted for another root, the patch no longer matches it, or its analysis was
incomplete. It skips (and lists) a file whose bytes changed since the draft, a path that
resolves outside the root, and, without `--allow-dirty`, a file git does not hold a clean
committed copy of, or every file when the root is not a git checkout.

Exit codes: 2 when the analysis fails or is incomplete (the proposal is still written), when
the output directory holds files this command did not write, or when `--apply` refuses to
run; 1 when `--apply` skipped a file; 0 otherwise.
"""
from __future__ import annotations

import argparse
import codecs
import difflib
import hashlib
import json
import os
import re
import stat
import subprocess
import tempfile
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from functools import cached_property
from pathlib import Path, PurePosixPath

from ..config import Config, load_config
from ..core import git
from ..core.files import is_test_path
from ..docs.coverage import _jsdoc_before
from ..impact.features import (CONFIDENT, HANDLER_EDGES, LAYERS, STORE_EDGES, FeatureGroup, edge_index,
                               endpoint_status, feature_groups, reach, route_path)
from ..lens.build import attached_source_id
from .audit import MARKABLE_SUFFIXES, REF_PATH_RE, STORE_TOKEN_RE, AuditContext, markers_for
from .model import iter_files as featuretrace_files
from .settings import FTSettings, from_config

DEFAULT_OUT = ".repolens/featuretrace-proposal"
GENERATOR = "repolens featuretrace propose"
#: Bounds that keep one block readable and inside the audit's 20-line window.
MAX_RELATED = 8
MAX_LISTED = 3
MAX_SEE = 5
MAX_EVIDENCE = 20
#: Consumers listed per concept in the owners draft; the rest are counted.
MAX_CONSUMERS = 10
#: A line this long is a bundle or minified output, not source a person maintains.
MINIFIED_LINE = 1000
JS_SUFFIXES = frozenset({".js", ".jsx", ".mjs", ".ts", ".tsx"})
FUNCTION_LENS_RE = re.compile(r"^\s*(?://|#)\s*@functionlens:([A-Za-z][A-Za-z0-9_.-]*)\s*$")
PLACEHOLDER = "TODO(repolens): describe what this does and who may call it."
REMARKS = "@remarks Generated by repolens from static evidence; review before relying on it."
#: Directory names whose files are one-off or third-party code: ranked after application code in
#: `Related:` and as a suggested owner.
LOW_RANK_DIRS = frozenset({"scripts", "script", "migrations", "migration", "tools", "vendor", "vendored",
                           "third_party"})
#: Where each proposal file carries its stamp, so a rerun never replaces a file a person wrote.
_README_STAMP = f"<!-- {GENERATOR}: "
_PATCH_STAMP = f"# {GENERATOR}: "
_OWNERS_STAMP = f"# DRAFT capability index written by `{GENERATOR}"

_TAG = re.compile(r"^[A-Za-z0-9_.-]+$")
#: Generated-file headers, matched in the comment lines among a file's first lines. Only standard forms
#: count: prose such as "do not edit this list without asking" is a note to maintainers, not a generated file.
GENERATED_HEADERS = (
    # Meta / Relay / Hack mark the FILE: `@generated`, `@generated by tool`, `@generated SignedSource<<…>>`.
    # A doc-comment tag with another value (`* @generated FunctionHeader`) marks one comment, not the file.
    re.compile(r"@generated(?:\s*(?:\*/|-->)?\s*$|\s+(?:by\b|SignedSource\b))"),
    re.compile(r"\bCode generated\b.*\bDO NOT EDIT\b"),              # Go convention
    re.compile(r"\bThis file (?:is|was|has been) (?:auto-?|automatically )?generated\b", re.I),
    re.compile(r"<auto-generated\b", re.I),                          # .NET / T4
    re.compile(r"^\s*(?://+|#+|/\*+|\*|<!--)?\s*DO NOT EDIT[.!]?\s*(?:\*/|-->)?\s*$", re.I),  # a whole comment line
)
_DIRECTIVE = re.compile(r"""^(['"])use [A-Za-z ]+\1;?$""")
#: PEP 263: an encoding declaration on line 1, or on line 2 below a comment or blank line.
_CODING = re.compile(r"^[ \t\f]*#.*?coding[:=][ \t]*([-_.a-zA-Z0-9]+)")
_OPERATION = re.compile(r"\((reads|writes|declares|deletes|updates)\b")
_STORE_WORDS = {"postgres_table": ("Table", "table"), "mongo_collection": ("Collection", "collection")}
_METHOD_ORDER = {m: i for i, m in enumerate(("GET", "POST", "PUT", "PATCH", "DELETE", "ANY"))}
_MARKER_LINE = re.compile(r"^(#|//)(?: [^\r\n]*)?$")


@dataclass
class Draft:
    """The blocks drafted for one file, and the bytes before and after them."""
    path: str
    group: str
    tag: str
    layer: str
    other_groups: list[str]
    sha256: str
    original: bytes
    updated: bytes = b""
    marker: list[str] = field(default_factory=list)
    marker_line: int = 0
    jsdoc: list[dict] = field(default_factory=list)
    function_lens: list[dict] = field(default_factory=list)
    evidence: list[str] = field(default_factory=list)
    audit_issues: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        """The draft as recorded in proposal.json: enough to apply it again without another analysis."""
        return {"path": self.path, "group": self.group, "tag": self.tag, "layer": self.layer,
                "other_groups": self.other_groups, "sha256": self.sha256,
                "marker": {"line": self.marker_line, "lines": self.marker} if self.marker else None,
                "jsdoc": self.jsdoc, "function_lens": self.function_lens,
                "evidence": self.evidence, "audit_issues": self.audit_issues}


@dataclass
class Proposal:
    """Every draft and every group file that was left alone, with the reason."""
    drafts: list[Draft]
    skipped: list[tuple[str, str]]
    tags: dict[str, str]


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _listed(items: list[str], limit: int = MAX_LISTED, separator: str = ", ") -> str:
    unique = list(dict.fromkeys(items))
    text = separator.join(unique[:limit])
    return f"{text} and {len(unique) - limit} more" if len(unique) > limit else text


def split_lines(text: str, *, keepends: bool = False) -> list[str]:
    """Lines split on `\\n` only. `str.splitlines` also splits on form feeds, `\\x85` and U+2028, which
    neither git nor the graph's line numbers count, so a patch built from it does not apply."""
    parts = text.split("\n")
    if keepends:
        return [part + "\n" for part in parts[:-1]] + ([parts[-1]] if parts[-1] else [])
    if parts and parts[-1] == "":
        parts.pop()
    return parts


def _low_rank(path: str) -> bool:
    return any(part.lower() in LOW_RANK_DIRS for part in PurePosixPath(path).parts[:-1])


def _operation(edge) -> str:
    """`reads`, `writes`, `declares`, ... from a store edge, or `touches` when it names none."""
    if edge.kind == "READS_STORE":
        return "reads"
    if edge.kind == "WRITES_STORE":
        return "writes"
    match = _OPERATION.search(edge.detail or "")
    return match.group(1) if match else "touches"


class _Evidence:
    """Indexes over one graph that the drafts read.

    Code reach follows confident edges only (`features.CONFIDENT`): a name-only call can land on any
    function with that name. A store reference counts unless it is `ambiguous`, comes from a regex match
    (`origin="regex"`), or names a store only regex matches found (`metadata.unverified`); a parsed SQL
    reference is `probable` by design (the live schema is never read) and counts. Calls from a page or
    client to a served route are route-shape matches, `probable` by design; only `ambiguous` ones, which
    name several handlers, are left out."""

    def __init__(self, graph, depth: int = 4):
        self.graph = graph
        self.depth = depth
        self.outgoing, self.incoming = edge_index(graph)
        self.status = endpoint_status(graph, self.outgoing, self.incoming)
        self.in_file: dict[str, list[str]] = defaultdict(list)
        for node in graph.nodes.values():
            if node.path and node.kind in {"file", "symbol"}:
                self.in_file[node.path].append(node.id)
        self._reached: dict[str, set[str]] = {}

    def path(self, node_id: str) -> str | None:
        node = self.graph.nodes.get(node_id)
        return node.path if node else None

    def served(self, endpoint: str) -> bool:
        return self.status.get(endpoint) == "served"

    def endpoint_label(self, endpoint: str) -> str:
        node = self.graph.nodes[endpoint]
        return f"{node.metadata.get('method') or node.label.split(' ', 1)[0]} {route_path(node)}"

    def edges_from(self, path: str, kind: str) -> list:
        return [e for node in self.in_file.get(path, ()) for e in self.outgoing.get(node, ()) if e.kind == kind]

    def page_ids(self, path: str) -> set[str]:
        """Ids of the pages `path` implements."""
        return {e.source for node in self.in_file.get(path, ()) for e in self.incoming.get(node, ())
                if e.kind == "IMPLEMENTED_BY" and self.graph.nodes[e.source].kind == "page"}

    def pages(self, path: str) -> list[str]:
        """Routes of the pages `path` implements."""
        return sorted({route_path(self.graph.nodes[page]) for page in self.page_ids(path)})

    def handled(self, path: str) -> list[tuple[str, object]]:
        """(endpoint id, edge) for the endpoints a node in `path` serves, as a scanned handler or a declared route."""
        return [(e.source, e) for node in self.in_file.get(path, ()) for e in self.incoming.get(node, ())
                if e.kind in HANDLER_EDGES and self.graph.nodes[e.source].kind == "endpoint"]

    def served_here(self, path: str) -> list[str]:
        """Served endpoints of `path`, without an artifact's second spelling of a route the scan found.

        A router artifact may declare `/api/orders` for a handler the scan registered as `/orders`
        (or the reverse); listing both says the file serves two routes."""
        served = sorted({endpoint for endpoint, _ in self.handled(path) if self.served(endpoint)})
        scanned = {endpoint for endpoint, edge in self.handled(path) if edge.kind == "HANDLES_API"}
        shapes = {endpoint: self.endpoint_label(endpoint).split(" ", 1) for endpoint in served}
        keep = []
        for endpoint in served:
            method, route = shapes[endpoint]
            if endpoint not in scanned and any(
                    shapes[other][0] == method and shapes[other][1] != route
                    and (shapes[other][1].endswith(route) or route.endswith(shapes[other][1]))
                    for other in scanned if other in shapes):
                continue
            keep.append(endpoint)
        return keep

    def handler_files(self, endpoint: str) -> set[str]:
        return {where for e in self.outgoing.get(endpoint, ()) if e.kind in HANDLER_EDGES
                if (where := self.path(e.target))}

    def callers(self, endpoint: str) -> list:
        """CALLS_API edges into `endpoint` from outside test code, ambiguous matches left out."""
        return [e for e in self.incoming.get(endpoint, ()) if e.kind == "CALLS_API" and e.resolution != "ambiguous"
                and (where := self.path(e.source)) and not is_test_path(where)]

    def api_calls(self, path: str) -> list:
        """CALLS_API edges from `path` to served endpoints, ambiguous matches left out."""
        return [e for e in self.edges_from(path, "CALLS_API") if e.resolution != "ambiguous" and self.served(e.target)]

    def reached(self, path: str) -> set[str]:
        """Nodes the handlers in `path` reach over confident calls, the handlers included."""
        if path not in self._reached:
            found: set[str] = set()
            for _endpoint, edge in self.handled(path):
                found |= reach(self.outgoing, edge.target, self.depth)
            self._reached[path] = found
        return self._reached[path]

    def server_calls(self, path: str) -> list[tuple[object, list[tuple[object, str, object]]]]:
        """(edge, stores) for each import-bound call or JSX hand-over from `path` to a function in
        another file whose confident reach touches a store: a Next.js server action or a server
        module a server component imports. Name-only matches never count."""
        found = []
        for edge in self.edges_from(path, "CALLS"):
            where = self.path(edge.target)
            if edge.origin != "import_binding" or edge.resolution not in CONFIDENT or not where \
                    or where == path or is_test_path(where):
                continue
            if stores := self.store_edges(reach(self.outgoing, edge.target, self.depth)):
                found.append((edge, stores))
        return found

    def server_callers(self, path: str) -> set[str]:
        """Files outside test code that import-bind and call (or hand over) a function in `path`."""
        return {where for node in self.in_file.get(path, ()) for e in self.incoming.get(node, ())
                if e.kind == "CALLS" and e.origin == "import_binding" and e.resolution in CONFIDENT
                and (where := self.path(e.source)) and where != path and not is_test_path(where)}

    def server_step(self, edge) -> str:
        """`action save` for a `"use server"` export, `server load` for any other server function."""
        node = self.graph.nodes[edge.target]
        directive = next((self.graph.nodes[n].metadata.get("directive") for n in self.in_file.get(node.path or "", ())
                          if self.graph.nodes[n].kind == "file"), None)
        name = node.metadata.get("qualified_name") or node.label
        return f"{'action' if directive == 'use server' else 'server'} {name}"

    @cached_property
    def reaching_endpoints(self) -> dict[str, set[str]]:
        """Path -> served endpoints whose handlers confidently reach a node in that path (the handler's file excluded)."""
        out: dict[str, set[str]] = defaultdict(set)
        for endpoint, status in self.status.items():
            if status != "served":
                continue
            for edge in self.outgoing.get(endpoint, ()):
                if edge.kind not in HANDLER_EDGES:
                    continue
                home = self.path(edge.target)
                for node in reach(self.outgoing, edge.target, self.depth):
                    where = self.path(node)
                    if where and where != home:
                        out[where].add(endpoint)
        return out

    def store_edge(self, edge) -> object | None:
        """The store `edge` references when it is store evidence a marker may name (see the class docstring)."""
        store = self.graph.nodes.get(edge.target)
        if (edge.kind in STORE_EDGES and store is not None and store.kind in _STORE_WORDS
                and edge.resolution != "ambiguous" and edge.origin != "regex"
                and not store.metadata.get("unverified")):
            return store
        return None

    def store_edges(self, node_ids) -> list[tuple[object, str, object]]:
        """(store, operation, edge) for the store references the given nodes make themselves."""
        return [(store, _operation(edge), edge) for node_id in node_ids for edge in self.outgoing.get(node_id, ())
                if (store := self.store_edge(edge)) is not None]

    def stores(self, path: str) -> list[tuple[object, str, object]]:
        """(store, operation, edge) for the store references the nodes of `path` make."""
        return self.store_edges(self.in_file.get(path, ()))

    def endpoint_stores(self, endpoint: str) -> list[tuple[object, str, object]]:
        """The store references the handlers of `endpoint` reach."""
        nodes: set[str] = set()
        for edge in self.outgoing.get(endpoint, ()):
            if edge.kind in HANDLER_EDGES:
                nodes |= reach(self.outgoing, edge.target, self.depth)
        return self.store_edges(nodes)

    def file_stores(self, path: str, layer: str) -> list[tuple[object, str, object]]:
        """The stores a marker on `path` names: a router's own and the ones its handlers reach, a
        service's own, a model's declared ones, and none for a frontend file."""
        if layer == "frontend":
            return []
        if layer == "router":
            return self.store_edges(set(self.in_file.get(path, ())) | self.reached(path))
        own = self.stores(path)
        return [item for item in own if item[1] == "declares"] if layer == "model" else own

    def referencing(self, store_ids, *, declaring: bool) -> Counter:
        """Files whose own code declares (or otherwise references) the given stores, with counts."""
        found: Counter = Counter()
        for store in store_ids:
            for edge in self.incoming.get(store, ()):
                if self.store_edge(edge) is not None and (_operation(edge) == "declares") == declaring:
                    if where := self.path(edge.source):
                        found[where] += 1
        return found


def _api_role(ev: _Evidence, endpoints) -> str:
    by_route: dict[str, set[str]] = defaultdict(set)
    for endpoint in endpoints:
        method, route = ev.endpoint_label(endpoint).split(" ", 1)
        by_route[route].add(method)
    return _listed([f"{', '.join(sorted(methods, key=lambda m: _METHOD_ORDER.get(m, 99)))} {route}"
                    for route, methods in sorted(by_route.items())], separator="; ")


def _store_names(stores) -> list[str]:
    return sorted({store.label for store in stores})


def _related(ev: _Evidence, path: str, layer: str) -> Counter:
    """Files with direct evidence linking them to `path`, with how much.

    router: the files calling its routes, the files its handlers reach and the files declaring its stores;
    frontend: the route files of the served endpoints it calls; service: the route files whose handlers
    reach it and the files declaring its stores; model: the files that reference its stores."""
    found: Counter = Counter()
    if layer == "router":
        for endpoint in ev.served_here(path):
            found.update(ev.path(e.source) for e in ev.callers(endpoint))
        found.update(ev.path(node) for node in ev.reached(path))
        found.update(ev.referencing({s.id for s, _, _ in ev.file_stores(path, layer)}, declaring=True))
    elif layer == "frontend":
        for edge in ev.api_calls(path):
            found.update(ev.handler_files(edge.target))
        found.update(ev.path(edge.target) for edge, _ in ev.server_calls(path))
    elif layer == "service":
        for endpoint in ev.reaching_endpoints.get(path, ()):
            found.update(ev.handler_files(endpoint))
        found.update(ev.server_callers(path))
        found.update(ev.referencing({s.id for s, _, _ in ev.stores(path)}, declaring=True))
    else:
        found.update(ev.referencing({s.id for s, _, _ in ev.file_stores(path, layer)}, declaring=False))
    return Counter({where: n for where, n in found.items() if where and where != path and not is_test_path(where)})


def _group_evidence(ev: _Evidence, group: FeatureGroup, path: str, layer: str) -> int:
    """How much evidence links `path` to `group`: its pages, the group's endpoints it serves, calls or is
    reached from, and the group's stores its marker would name."""
    endpoints = set(group.endpoints)
    score = len(ev.page_ids(path) & set(group.pages))
    score += len({endpoint for endpoint, _ in ev.handled(path)} & endpoints)
    score += len({edge.target for edge in ev.api_calls(path)} & endpoints)
    score += len(ev.reaching_endpoints.get(path, set()) & endpoints)
    score += len({store.id for store, _, _ in ev.file_stores(path, layer)} & set(group.stores))
    return score


def _role_and_flow(ev: _Evidence, path: str, layer: str, stores, group: str) -> tuple[str, list[str]]:
    """The marker's one-line role and its Data flow steps, from served endpoints and confident reach."""
    names = _store_names(store for store, _, _ in stores)
    name = PurePosixPath(path).name
    if layer == "router":
        served = ev.served_here(path)
        callers: list[str] = []
        for endpoint in served:
            for edge in ev.callers(endpoint):
                where = ev.path(edge.source)
                pages = ev.pages(where)
                if pages:
                    callers.extend(f"page {page}" for page in pages)
                else:
                    callers.append(where)
        api = _api_role(ev, served)
        return f"API {api}", [_listed(callers) or "no static caller found", api, _listed(names) or "no store found"]
    if layer == "model":
        return (f"declares {_listed(names)}" if names else f"model code in {name}",
                [name, "declares", _listed(names) or "no declared store found"])
    if layer == "service":
        operations: dict[str, set[str]] = defaultdict(set)
        for store, operation, _ in stores:
            operations[store.label].add(operation)
        functions = sorted({ev.graph.nodes[edge.source].metadata.get("qualified_name") or ev.graph.nodes[edge.source].label
                            for _, _, edge in stores if ev.graph.nodes[edge.source].kind == "symbol"})
        routes = sorted(ev.endpoint_label(e) for e in ev.reaching_endpoints.get(path, ()))
        called = sorted({ev.endpoint_label(e.target) for e in ev.api_calls(path)})
        sink = [f"{n} ({', '.join(sorted(operations[n]))})" for n in names]
        if names:
            role = f"data access for {_listed(names)}"
        elif called:
            role = f"API client for {_listed(called)}"
        else:
            role = f"code the {group} routes reach"
        if routes:
            source = f"API {_listed(routes)}"
        else:
            # A server action or server module: the pages (or other files) that import and call it.
            callers = ev.server_callers(path)
            pages = sorted({page for where in callers for page in ev.pages(where)})
            source = (f"page {_listed(pages)}" if pages else _listed(sorted(callers))) or "no route found"
        return role, [source, _listed(functions) or name, _listed(sink) or _listed(called) or "no store found"]
    pages = ev.pages(path)
    calls = ev.api_calls(path)
    server = ev.server_calls(path)
    api = sorted({ev.endpoint_label(edge.target) for edge in calls})
    actions = sorted({ev.server_step(edge) for edge, _ in server})
    called = api + actions
    own = ev.stores(path)  # a server component's own queries (`withUser(db, (tx) => tx.many(…))`)
    reached = _store_names([store for edge in calls for store, _, _ in ev.endpoint_stores(edge.target)]
                           + [store for _, stores in server for store, _, _ in stores] + [store for store, _, _ in own])
    if own:
        called = [*called, "queries in this file"]
    if pages:
        role = f"page {_listed(pages)}"
    elif api:
        role = f"API client for {_listed(api)}"
    elif actions:
        role = f"UI calling {_listed(actions)}"
    else:
        role = f"UI for {group}"
    steps = [f"page {_listed(pages)}" if pages else "browser", _listed(called) or "no served API call or server function found"]
    if reached:
        steps.append(_listed(reached))
    return role, steps


def _coding(lines: list[str]) -> tuple[int, str] | None:
    """(line index, encoding) of a PEP 263 declaration: line 1, or line 2 below a comment or blank line."""
    for index in (0, 1):
        if index >= len(lines):
            break
        line = lines[index].lstrip("﻿")
        if match := _CODING.match(line):
            return index, match.group(1)
        if line.strip() and not line.lstrip().startswith("#"):
            break
    return None


def _utf8(encoding: str) -> bool:
    try:
        return codecs.lookup(encoding).name in {"utf-8", "utf-8-sig"}
    except LookupError:
        return False


def _marker_index(lines: list[str], python: bool) -> tuple[int, int]:
    """(preferred, earliest) line index for a marker.

    Python: after a shebang and an encoding declaration (both indexes agree). JS/TS: preferably after a
    directive prologue (`"use client"`), which may follow comments; the earliest valid place is the top
    (after a shebang), since a comment before a directive leaves it a directive."""
    top = 1 if lines and lines[0].lstrip("﻿").startswith("#!") else 0
    if python:
        coding = _coding(lines)
        index = max(top, coding[0] + 1) if coding else top
        return index, index
    probe, end = top, top
    while probe < len(lines):
        text = lines[probe].lstrip("﻿").strip()
        if _DIRECTIVE.match(text):
            end = probe + 1
        elif text and not text.startswith("//"):
            break
        probe += 1
    return end, top


def _jsdoc_blocks(ev: _Evidence, path: str, lines: list[str]) -> list[tuple[int, list[str], str]]:
    """(line index, block lines, symbol) for exported handlers and data access with no JSDoc."""
    blocks = []
    handled = defaultdict(list)
    for endpoint, edge in ev.handled(path):
        handled[edge.target].append(endpoint)
    for node_id in ev.in_file.get(path, ()):
        node = ev.graph.nodes[node_id]
        qualified = node.metadata.get("qualified_name") or ""
        if node.kind != "symbol" or not node.metadata.get("exported") or "." in qualified or not node.line:
            continue
        stores = [(s, op) for s, op, e in ev.stores(path) if e.source == node_id]
        endpoints = handled.get(node_id, [])
        if not (stores or endpoints):
            continue
        index = node.line - 1
        if index >= len(lines) or qualified not in lines[index]:
            continue  # the recorded line does not hold the declaration: do not guess
        if _jsdoc_before(lines, index) is not None:
            continue
        while index > 0 and lines[index - 1].strip().startswith("@"):
            index -= 1
        indent = lines[index][:len(lines[index]) - len(lines[index].lstrip())]
        facts = [f"Handles `{ev.endpoint_label(e)}`." for e in sorted(set(endpoints))]
        for store, operation in sorted(set((s.label, op) for s, op in stores)):
            kind = next(s.kind for s, _ in stores if s.label == store)
            verb = operation.capitalize() if operation != "touches" else "Uses"
            facts.append(f"{verb} {_STORE_WORDS[kind][1]} `{store}`.")
        sees = sorted({ev.path(e.source) for endpoint in endpoints for e in ev.callers(endpoint)}
                      | {ev.path(e.source) for e in ev.incoming.get(node_id, ())
                         if e.kind == "CALLS" and e.resolution in CONFIDENT} - {path, None})
        sees = [s for s in sees if s and not is_test_path(s)][:MAX_SEE]
        body = [PLACEHOLDER, "", *facts, *(f"@see {s}" for s in sees), REMARKS]
        block = [f"{indent}/**", *(f"{indent} * {line}".rstrip() for line in (b.replace("*/", "* /") for b in body)),
                 f"{indent} */"]
        blocks.append((index, block, qualified))
    return sorted(blocks)


def _function_lens_id(path: str, qualified: str) -> str:
    """A deterministic seed for an annotation that becomes stable once committed with the function.

    The path and qualified name only create the first value. Function Lens subsequently reads the
    comment, so the id survives a rename or move when the comment moves with the declaration.
    """
    seed = hashlib.sha256(f"{path}::{qualified}".encode()).hexdigest()[:16]
    return f"fn-{seed}"


def _has_function_lens_id(lines: list[str], index: int) -> bool:
    """Whether the declaration at `index` already has an attached Function Lens id.

    Function Lens's own rule (`attached_source_id`), so a draft never adds a second id to a
    declaration the index already reads one from, nor reuses the previous declaration's.
    """
    return attached_source_id(lines, index) is not None


def _function_lens_blocks(ev: _Evidence, path: str, lines: list[str], *, python: bool,
                          layer: str) -> list[tuple[int, list[str], str, str]]:
    """Stable id comments for public, top-level functions on a feature boundary.

    Route handlers, functions that call an API or touch a store, and exported frontend entry
    functions are useful navigation anchors. Local helpers stay source-free in the normal Function
    Lens index, avoiding a comment on every function in a large repository.
    """
    handled = {edge.target for _endpoint, edge in ev.handled(path)}
    blocks = []
    for node_id in ev.in_file.get(path, ()):
        node = ev.graph.nodes[node_id]
        qualified = str(node.metadata.get("qualified_name") or "")
        if node.kind != "symbol" or not qualified or "." in qualified or not node.line:
            continue
        public = not qualified.startswith("_") if python else bool(node.metadata.get("exported"))
        outgoing = ev.outgoing.get(node_id, ())
        boundary = (node_id in handled or any(e.kind in STORE_EDGES | {"CALLS_API"} for e in outgoing)
                    or (layer == "frontend" and not python and public))
        if not public or not boundary:
            continue
        index = node.line - 1
        if index >= len(lines) or node.label not in lines[index] or _has_function_lens_id(lines, index):
            continue
        while index > 0 and lines[index - 1].strip().startswith("@"):
            index -= 1
        if _jsdoc_before(lines, index) is not None:
            end = index - 1
            while end >= 0 and (not lines[end].strip() or lines[end].strip().startswith(("//", "@"))):
                end -= 1
            start = end
            while start >= 0 and "/**" not in lines[start]:
                start -= 1
            if start >= 0:
                index = start
        stable_id = _function_lens_id(path, qualified)
        leader = "#" if python else "//"
        blocks.append((index, [f"{leader} @functionlens:{stable_id}"], qualified, stable_id))
    return sorted(blocks)


def _insert(text: str, insertions: list[tuple[int, int, list[str]]]) -> str:
    """`text` with each (line index, order, lines) inserted before that line, keeping BOM and newlines.

    Inserted lines take the file's majority line ending."""
    bom = text.startswith("﻿")
    body = text[1:] if bom else text
    crlf = body.count("\r\n")
    newline = "\r\n" if crlf > body.count("\n") - crlf else "\n"
    lines = split_lines(body, keepends=True)
    out: list[str] = []
    by_index: dict[int, list[list[str]]] = defaultdict(list)
    for index, _order, block in sorted(insertions, key=lambda item: (item[0], item[1])):
        by_index[index].append(block)
    for index in range(len(lines) + 1):
        for block in by_index.get(index, ()):
            if index == len(lines):
                if out and not out[-1].endswith("\n"):
                    out[-1] += newline
                    out.extend(line + newline for line in block[:-1])
                    out.append(block[-1])
                    continue
            out.extend(line + newline for line in block)
        if index < len(lines):
            out.append(lines[index])
    return ("﻿" if bom else "") + "".join(out)


def with_blocks(text: str, marker: tuple[int, list[str]] | None, jsdoc: list[tuple[int, list[str]]],
                function_lens: list[tuple[int, list[str]]] | None = None) -> str:
    """`text` with a marker block, JSDoc and Function Lens id comments inserted.

    The drafting run and `--apply` both build the updated file through here, so the bytes `--apply`
    writes are the ones the reviewed patch shows."""
    lines = split_lines(text.lstrip("﻿"))
    insertions: list[tuple[int, int, list[str]]] = []
    if marker:
        index, block = marker
        block = list(block)
        if index < len(lines) and lines[index].strip():
            block.append("")
        insertions.append((index, 0, block))
    insertions += [(index, 1, list(block)) for index, block in (function_lens or [])]
    insertions += [(index, 2, list(block)) for index, block in jsdoc]
    return _insert(text, insertions)


def _diff(path: str, before: str, after: str) -> str:
    """A unified diff `git apply` accepts, with the no-newline marker difflib leaves out."""
    lines = [f"diff --git a/{path} b/{path}\n"]
    for line in difflib.unified_diff(split_lines(before, keepends=True), split_lines(after, keepends=True),
                                     f"a/{path}", f"b/{path}"):
        lines.append(line if line.endswith("\n") else line + "\n\\ No newline at end of file\n")
    return "".join(lines)


def _comment_lines(lines: list[str]) -> list[str]:
    """The comment lines (and leading docstring lines) among `lines`: a string literal in code is not a header."""
    found: list[str] = []
    closing: str | None = None
    for line in lines:
        text = line.strip()
        if closing:
            found.append(text)
            if closing in text:
                closing = None
            continue
        if text.startswith(("//", "#", "*")):
            found.append(text)
        elif text.startswith(("/*", "<!--", '"""', "'''")):
            found.append(text)
            opener = next(o for o in ("/*", "<!--", '"""', "'''") if text.startswith(o))
            end = {"/*": "*/", "<!--": "-->"}.get(opener, opener)
            if end not in text[len(opener):]:
                closing = end
    return found


def _unusable(root: Path, path: str, raw: bytes | None, max_bytes: int) -> str | None:
    if raw is None:
        return "not a readable file inside the root"
    if len(raw) > max_bytes:
        return f"larger than max_file_bytes ({max_bytes})"
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        return "not UTF-8 text"
    lines = split_lines(text.lstrip("﻿"))
    if any(len(line) > MINIFIED_LINE for line in lines) or ".min." in PurePosixPath(path).name:
        return "minified"
    for line in _comment_lines(lines[:5]):
        if any(pattern.search(line) for pattern in GENERATED_HEADERS):
            return f"generated (header: {line[:80]})"
    if path.endswith(".py") and (coding := _coding(lines)) and not _utf8(coding[1]):
        return f"declares the {coding[1]} encoding, which cannot hold the marker's `—` and `→`"
    return None


def _read_inside(root: Path, path: str) -> bytes | None:
    target = root / path
    try:
        resolved = target.resolve(strict=True)
    except OSError:
        return None
    if not resolved.is_relative_to(root.resolve()) or not resolved.is_file():
        return None
    try:
        return resolved.read_bytes()
    except OSError:
        return None


def _predicted_issues(settings: FTSettings, root: Path, drafts: list[Draft]) -> None:
    """Run the audit's checks over each drafted marker as if every draft were applied; record what it would report.

    The audit reads a 20-line window under the marker, so a path in the code under it (an ES module
    `import … from "../lib/db.js"`) can be reported as a dangling reference; that is listed too."""
    ctx = AuditContext(settings)
    index = dict(ctx.tag_index)
    for draft in drafts:
        if draft.marker:
            key = (root / draft.path).resolve().as_posix()
            index[key] = frozenset(index.get(key, frozenset()) | {draft.tag})
    ctx._tag_index = index
    for draft in drafts:
        if not draft.marker:
            continue
        markers = markers_for(ctx, root / draft.path, draft.updated.decode("utf-8").lstrip("﻿"))
        mine = [m for m in markers if m.line_no == draft.marker_line]
        draft.audit_issues = list(mine[0].issues) if mine else ["the audit does not find the drafted marker"]


def build_proposal(root: Path, graph, settings: FTSettings, *, max_file_bytes: int,
                   tags: dict[str, str] | None = None, only: set[str] | None = None,
                   jsdoc: bool = False, function_lens: bool = False) -> Proposal:
    """Draft markers and requested documentation for every feature group in `graph`.

    Raises ValueError when `tags` or `only` name a group that does not exist."""
    root = root.resolve()
    ev = _Evidence(graph)
    groups = feature_groups(graph)
    unknown = sorted((set(tags or {}) | set(only or ())) - set(groups))
    if unknown:
        raise ValueError(f"no feature group named {', '.join(unknown)}; the groups are: {', '.join(groups) or 'none'}")
    tags = {name: (tags or {}).get(name, name) for name in groups}
    markable = MARKABLE_SUFFIXES & settings.extensions
    scanned = {path.relative_to(settings.root).as_posix() for path in featuretrace_files(settings)}
    tracked = git.tracked_paths(root)
    options: dict[str, list[tuple[tuple[int, int, str], str]]] = defaultdict(list)
    skipped: list[tuple[str, str]] = []
    for name, group in groups.items():
        if only and name not in only:
            continue
        for path, layer in group.files.items():
            if PurePosixPath(path).suffix not in markable or is_test_path(path):
                continue
            # The group with the most evidence linking the file wins; a shared model file is not
            # tagged with whichever group sorts first.
            key = (-_group_evidence(ev, group, path, layer), LAYERS.index(layer), name)
            options[path].append((key, name))
    chosen = {}
    for path, found in options.items():
        if path in scanned:
            chosen[path] = min(found)[1]
        else:
            skipped.append((path, "outside [featuretrace] scan_dirs or under skip_parts, so the audit would not read it"))
    texts: dict[str, tuple[bytes, str]] = {}
    marked: set[str] = set()
    positions: dict[str, int] = {}
    for path in sorted(chosen):
        raw = _read_inside(root, path)
        reason = _unusable(root, path, raw, max_file_bytes)
        if reason:
            skipped.append((path, reason))
            continue
        text = raw.decode("utf-8")
        if "@featuretrace:" in text:
            marked.add(path)
        else:
            preferred, earliest = _marker_index(split_lines(text.lstrip("﻿")), path.endswith(".py"))
            index = next((i for i in (preferred, earliest) if i + 1 <= settings.near_top_lines), None)
            if index is None:
                skipped.append((path, f"its header would put the marker below line {settings.near_top_lines}"))
                continue
            positions[path] = index
        texts[path] = (raw, text)

    def relatable(path: str) -> bool:
        # The audit reports a reference git does not track as nonexistent, requires a markable Related:
        # target to carry a marker, and checks that any path-like reference exists.
        if tracked and path not in tracked:
            return False
        if PurePosixPath(path).suffix in MARKABLE_SUFFIXES:
            return path in marked or path in positions
        return not REF_PATH_RE.fullmatch(path) and (root / path).is_file()

    drafts: list[Draft] = []
    for path, (raw, text) in texts.items():
        name = chosen[path]
        group = groups[name]
        layer = group.files[path]
        lines = split_lines(text.lstrip("﻿"))
        others = [other for _key, other in sorted(options[path]) if other != name]
        draft = Draft(path, name, tags[name], layer, others, _sha(raw), raw)
        python = path.endswith(".py")
        stores = ev.file_stores(path, layer)
        related = _related(ev, path, layer)
        marker: tuple[int, list[str]] | None = None
        if path in marked:
            if not ((jsdoc and not python) or function_lens):
                skipped.append((path, "already carries a @featuretrace marker"))
                continue
        else:
            index = positions[path]
            leader = "#" if python else "//"
            role, steps = _role_and_flow(ev, path, layer, stores, name)
            # Files of this group first, one-off scripts and vendored code last, then the most links.
            ranked = sorted(related.items(), key=lambda item: (item[0] not in group.files, _low_rank(item[0]),
                                                               -item[1], item[0]))
            listed = [other for other, _n in ranked if relatable(other)][:MAX_RELATED]
            body = [f"@featuretrace:{tags[name]} — {role} (draft)", f"Layer: {layer}",
                    f"Data flow: {' → '.join(steps)} (draft)."]
            # The audit requires the field; the maps read `none found` as no file.
            body.append(f"Related: {listed[0]}" if listed else "Related: none found (draft)")
            body.extend(f"  {other}" for other in listed[1:])
            for kind, (label, _) in _STORE_WORDS.items():
                names = sorted({store.label for store, _, _ in stores
                                if store.kind == kind and STORE_TOKEN_RE.match(store.label)})
                if names:
                    body.append(f"{label}: {', '.join(names)}")
            draft.marker = [f"{leader} {line}" for line in body]
            draft.marker_line = index + 1
            marker = (index, draft.marker)
        jsdoc_blocks: list[tuple[int, list[str]]] = []
        if jsdoc and not python and PurePosixPath(path).suffix in JS_SUFFIXES:
            for index, block, symbol in _jsdoc_blocks(ev, path, lines):
                jsdoc_blocks.append((index, block))
                draft.jsdoc.append({"symbol": symbol, "line": index + 1, "lines": block})
        function_lens_blocks: list[tuple[int, list[str]]] = []
        if function_lens:
            for index, block, symbol, stable_id in _function_lens_blocks(ev, path, lines, python=python, layer=layer):
                function_lens_blocks.append((index, block))
                draft.function_lens.append({"symbol": symbol, "id": stable_id,
                                            "line": index + 1, "lines": block})
        if marker is None and not jsdoc_blocks and not function_lens_blocks:
            skipped.append((path, "already carries a @featuretrace marker and needs no requested symbol documentation"))
            continue
        draft.updated = with_blocks(text, marker, jsdoc_blocks, function_lens_blocks).encode("utf-8")
        evidence = [f"page {page}" for page in ev.pages(path)]
        evidence += [f"{ev.endpoint_label(endpoint)} served at {edge.evidence} ({edge.resolution})"
                     for endpoint, edge in ev.handled(path)]
        evidence += [f"called from {e.evidence} ({e.resolution})" for endpoint in ev.served_here(path)
                     for e in ev.callers(endpoint)]
        evidence += [f"calls {ev.endpoint_label(e.target)} at {e.evidence} ({e.resolution})" for e in ev.api_calls(path)]
        evidence += [f"reached from {label}" for label in sorted(ev.endpoint_label(e) for e in ev.reaching_endpoints.get(path, ()))]
        evidence += [f"{operation} {store.label} at {edge.evidence} ({edge.resolution})" for store, operation, edge in stores]
        evidence += [f"related {other}: {count} link(s)" for other, count in sorted(related.items(), key=lambda i: (-i[1], i[0]))]
        draft.evidence = list(dict.fromkeys(evidence))[:MAX_EVIDENCE]
        drafts.append(draft)
    drafts.sort(key=lambda d: d.path)
    _predicted_issues(settings, root, drafts)
    return Proposal(drafts, sorted(skipped), tags)


def _yaml_string(value: str) -> str:
    """A YAML double-quoted scalar: JSON escapes, raw printable Unicode (an emoji path round-trips), and
    `\\u`/`\\U` escapes for the line and paragraph separators YAML would read as a line break."""
    text = json.dumps(value, ensure_ascii=False)
    return "".join(ch if ch.isprintable() or ch in "\t" else
                   (f"\\u{ord(ch):04x}" if ord(ch) <= 0xFFFF else f"\\U{ord(ch):08x}") for ch in text)


def owners_draft(graph, tags: dict[str, str], file_tags: dict[str, str] | None = None, *,
                 javascript_extensions: tuple[str, ...] = (".js", ".jsx", ".ts", ".tsx")) -> str:
    """A capability-index draft: one concept per store, owned by the non-route file whose own code references it most.

    Owners are Python files or JS/TS files with an extension `repolens owners` reads
    (`[owners] javascript_extensions`); a feature group's own files and then application code (not
    `LOW_RANK_DIRS`) are preferred. Consumers are the other files referencing the store themselves, the
    files calling the owner's functions through a confident edge, and the route files whose handlers
    confidently reach the owner; at most `MAX_CONSUMERS` are listed."""
    ev = _Evidence(graph)
    groups = feature_groups(graph)
    router_files = {where for endpoint in ev.status for where in ev.handler_files(endpoint)}
    store_groups: dict[str, list[str]] = defaultdict(list)
    group_files: dict[str, set[str]] = defaultdict(set)
    for name, group in groups.items():
        for store in group.stores:
            store_groups[store].append(tags.get(name, name))
            group_files[store] |= set(group.files)
    ownable = {".py", *javascript_extensions}
    lines = [f"{_OWNERS_STAMP} --owners`.",
             "# Each owner below is only the file outside route handlers whose own code references the",
             "# store most. Ownership is a human decision: confirm or replace every entry, write the",
             "# rule and a detect pattern, then move it into the registry `repolens owners` reads.",
             "version: 1", "concepts:"]
    count = 0
    for store in sorted((n for n in graph.nodes.values() if n.kind in _STORE_WORDS), key=lambda n: (n.kind, n.label)):
        references: Counter = Counter()
        symbols: dict[str, set[str]] = defaultdict(set)
        touching: dict[str, set[str]] = defaultdict(set)
        for edge in ev.incoming.get(store.id, ()):
            source = graph.nodes.get(edge.source)
            where = source.path if source else None
            if ev.store_edge(edge) is None or not where or is_test_path(where) or PurePosixPath(where).suffix not in ownable:
                continue
            references[where] += 1
            touching[where].add(source.id)
            qualified = source.metadata.get("qualified_name") or ""
            if source.kind == "symbol" and qualified and "." not in qualified:
                symbols[where].add(qualified)
        word = _STORE_WORDS[store.kind][1]
        candidates = [p for p in references if p not in router_files]
        if not candidates:
            lines.append(f"  # {word} {store.label}: no reference outside route handlers "
                         "from a file `repolens owners` reads; no owner drafted.")
            continue
        owner = min(candidates, key=lambda p: (p not in group_files[store.id], _low_rank(p), -references[p], p))
        consumers = set(references) - {owner}
        for node_id in touching[owner]:
            consumers.update(ev.path(e.source) for e in ev.incoming.get(node_id, ())
                             if e.kind in {"CALLS", "RENDERS"} and e.resolution in CONFIDENT)
        for endpoint in ev.reaching_endpoints.get(owner, ()):
            consumers.update(ev.handler_files(endpoint))
        consumers = sorted(c for c in consumers if c and c != owner and not is_test_path(c))
        entry = [
            f"  - concept: {_yaml_string(f'{word} {store.label}')}",
            f"    language: {_yaml_string('python' if owner.endswith('.py') else 'javascript')}",
            f"    owner: {_yaml_string(owner)}",
            f"    symbols: [{', '.join(_yaml_string(s) for s in sorted(symbols[owner]))}]",
            f"    rule: {_yaml_string(f'Draft: read and write {word} `{store.label}` through {owner}.')}",
            f"    why: {_yaml_string(f'Drafted by repolens from {references[owner]} static reference(s) in {owner}, the most outside route handlers. Ownership is a human decision.')}",
            "    detect: null",
            "    allow: []",
            "    known_violations: []",
            "    tests: []",
        ]
        tag = (file_tags or {}).get(owner) or (store_groups[store.id][0] if len(store_groups[store.id]) == 1 else None)
        if tag:
            entry.append(f"    featuretrace_tags: [{_yaml_string(tag)}]")
        if consumers:
            entry.append("    consumers:")
            for consumer in consumers[:MAX_CONSUMERS]:
                pages = ev.pages(consumer)
                served = ev.served_here(consumer)
                surface = (f"page {_listed(pages)}" if pages else f"API {_api_role(ev, served)}" if served
                           else "TODO(repolens): name what a user sees here")
                entry += [f"      - path: {_yaml_string(consumer)}", f"        surface: {_yaml_string(surface)}"]
            if len(consumers) > MAX_CONSUMERS:
                entry.append(f"      # and {len(consumers) - MAX_CONSUMERS} more consumers not listed")
        else:
            entry.append("    consumers: []")
        lines.extend(entry)
        count += 1
    if not count:
        lines[lines.index("concepts:")] = "concepts: []"
    return "\n".join(lines) + "\n"


def _in_git(root: Path) -> bool:
    try:
        result = git.run_git(root, "rev-parse", "--is-inside-work-tree", timeout=30)
    except (OSError, ValueError, subprocess.SubprocessError):
        return False
    return result.returncode == 0 and result.stdout.strip() == "true"


def _git_literal(root: Path, *args: str) -> subprocess.CompletedProcess:
    # `--literal-pathspecs`: `app/[id]/page.tsx` is a file name, not a glob matching `app/i/page.tsx`.
    return git.run_git(root, "--literal-pathspecs", *args, timeout=60)


def _clean_in_git(root: Path, relative: str) -> str | None:
    """Why git holds no clean committed copy of `relative`, or None when it does."""
    try:
        tracked = _git_literal(root, "ls-files", "--error-unmatch", "--", relative).returncode == 0
        if not tracked:
            return "not committed to git (pass --allow-dirty to write it anyway)"
        results = [_git_literal(root, "diff-index", "--quiet", "HEAD", "--", relative),
                   _git_literal(root, "diff-files", "--quiet", "--", relative)]
    except (OSError, subprocess.SubprocessError):
        return "git could not say whether it has uncommitted changes (pass --allow-dirty to write it anyway)"
    if any(result.returncode not in (0, 1) for result in results):
        return "git could not say whether it has uncommitted changes (pass --allow-dirty to write it anyway)"
    if any(result.returncode == 1 for result in results):
        return "has uncommitted changes (commit them or pass --allow-dirty)"
    return None


def _refusal(root: Path, draft: Draft, in_git: bool, allow_dirty: bool) -> str | None:
    target = root / draft.path
    try:
        resolved = target.resolve(strict=True)
    except OSError:
        return "no longer exists"
    if not resolved.is_relative_to(root.resolve()):
        return "resolves outside the repository root"
    try:
        current = resolved.read_bytes()
    except OSError:
        return "cannot be read"
    if _sha(current) != draft.sha256 or not draft.updated:
        return "changed since the proposal was drafted"
    if in_git and not allow_dirty:
        return _clean_in_git(root, resolved.relative_to(root.resolve()).as_posix())
    return None


def _write_atomically(target: Path, data: bytes) -> None:
    mode = stat.S_IMODE(target.stat().st_mode)
    handle, temporary = tempfile.mkstemp(dir=target.parent, prefix=f".{target.name}.", suffix=".repolens")
    try:
        with os.fdopen(handle, "wb") as stream:
            stream.write(data)
        os.chmod(temporary, mode)
        os.replace(temporary, target)
    except BaseException:
        Path(temporary).unlink(missing_ok=True)
        raise


def apply_drafts(root: Path, drafts: list[Draft], *, allow_dirty: bool) -> tuple[list[str], list[tuple[str, str]]]:
    """Write each draft that is still safe to write; (applied paths, (skipped path, reason))."""
    root = root.resolve()
    in_git = _in_git(root)
    if not in_git and not allow_dirty:
        return [], [(d.path, "not a git checkout: nothing could restore it (pass --allow-dirty to write anyway)")
                    for d in drafts]
    applied: list[str] = []
    skipped: list[tuple[str, str]] = []
    for draft in drafts:
        reason = _refusal(root, draft, in_git, allow_dirty)
        if reason is None:
            try:
                _write_atomically((root / draft.path).resolve(), draft.updated)
            except OSError as exc:
                reason = f"could not be written ({type(exc).__name__})"
        if reason:
            skipped.append((draft.path, reason))
        else:
            applied.append(draft.path)
    return applied, skipped


# ── the proposal directory ─────────────────────────────────────────────────────
def _ours(path: Path) -> bool:
    """Whether `path` is a regular file this command wrote: it carries the stamp where the command puts it."""
    try:
        if path.is_symlink() or not path.is_file():
            return False
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    if path.name == "proposal.json":
        try:
            data = json.loads(text)
        except ValueError:
            return False
        return isinstance(data, dict) and data.get("generator") == GENERATOR
    first = text.split("\n", 1)[0]
    stamp = {"README.md": _README_STAMP, "proposal.patch": _PATCH_STAMP,
             "canonical_owners.draft.yaml": _OWNERS_STAMP}.get(path.name)
    return bool(stamp) and first.startswith(stamp)


def _guard_out(out: Path, names: list[str]) -> None:
    """Refuse (ValueError) to write through a symlink or over a file this command did not write."""
    linked = [path for path in (out, *(out / name for name in names)) if path.is_symlink()]
    if linked:
        raise ValueError(f"refusing to write through a symlink: {', '.join(map(str, linked))}")
    foreign = [out / name for name in names if (out / name).exists() and not _ours(out / name)]
    if foreign:
        raise ValueError(f"refusing to overwrite {len(foreign)} file(s) not written by {GENERATOR}: "
                         f"{', '.join(map(str, foreign))}; pass a dedicated --out")


def _patch(drafts: list[Draft], build: str) -> str:
    return _PATCH_STAMP + build + "\n" + "".join(
        _diff(d.path, d.original.decode("utf-8"), d.updated.decode("utf-8")) for d in drafts)


def _check_comment_block(lines: object, kind: str, python: bool) -> list[str]:
    if not isinstance(lines, list) or not lines or not all(isinstance(line, str) and "\n" not in line
                                                           and "\r" not in line for line in lines):
        raise ValueError(f"malformed {kind} lines")
    if kind == "marker":
        leader = "#" if python else "//"
        if not all(_MARKER_LINE.match(line) and line.startswith(leader) for line in lines) or "@featuretrace:" not in lines[0]:
            raise ValueError("a marker line is not a comment")
    elif kind == "jsdoc":
        inner = [line.strip() for line in lines[1:-1]]
        if (lines[0].strip() != "/**" or lines[-1].strip() != "*/"
                or not all(line.startswith("*") and "*/" not in line for line in inner)):
            raise ValueError("a JSDoc block is not a comment")
    else:
        leader = "#" if python else "//"
        if not all(_MARKER_LINE.match(line) and line.startswith(leader) for line in lines):
            raise ValueError(f"a {kind} line is not a comment")
    return lines


def load_saved(root: Path, out: Path) -> tuple[dict, list[Draft], list[tuple[str, str]]]:
    """(payload, drafts, skipped) from the proposal a drafting run saved in `out`.

    Each draft is rebuilt from the current file through `with_blocks` and must equal the saved patch,
    so what is written is what was reviewed. Raises ValueError when there is no saved proposal, it was
    drafted for another root, or it is malformed; a file whose bytes changed is returned with no update
    (`apply_drafts` then skips it)."""
    json_path, patch_path = out / "proposal.json", out / "proposal.patch"
    if not _ours(json_path) or not _ours(patch_path):
        raise ValueError(f"no proposal drafted by {GENERATOR} in {out}; run it without --apply and review the patch first")
    try:
        payload = json.loads(json_path.read_text(encoding="utf-8"))
        saved_patch = patch_path.read_bytes().decode("utf-8")  # no newline translation: CRLF files stay CRLF
    except (OSError, ValueError) as exc:
        raise ValueError(f"cannot read the saved proposal: {exc}") from exc
    if payload.get("root") != root.resolve().as_posix():
        raise ValueError(f"the saved proposal was drafted for {payload.get('root')!r}, not this repository")
    files = payload.get("files")
    if not isinstance(files, list):
        raise ValueError("malformed proposal.json: no file list")
    drafts: list[Draft] = []
    changed: list[tuple[str, str]] = []
    body = saved_patch.split("\n", 1)[1] if "\n" in saved_patch else ""
    sections = [part for part in re.split(r"(?m)^(?=diff --git )", body) if part]
    if len(sections) != len(files):
        raise ValueError("proposal.patch and proposal.json list different files; draft the proposal again")
    for item in files:
        if not isinstance(item, dict) or not isinstance(item.get("path"), str) or not isinstance(item.get("sha256"), str):
            raise ValueError("malformed proposal.json: a file entry has no path or hash")
        path = item["path"]
        if PurePosixPath(path).is_absolute() or ".." in PurePosixPath(path).parts:
            raise ValueError(f"malformed proposal.json: {path!r} is not a path inside the repository")
        python = path.endswith(".py")
        marker_item = item.get("marker")
        marker = None
        if marker_item is not None:
            if not isinstance(marker_item, dict) or not isinstance(marker_item.get("line"), int):
                raise ValueError(f"malformed proposal.json: marker of {path}")
            marker = (marker_item["line"] - 1, _check_comment_block(marker_item.get("lines"), "marker", python))
        blocks = []
        for block in item.get("jsdoc") or []:
            if python or not isinstance(block, dict) or not isinstance(block.get("line"), int):
                raise ValueError(f"malformed proposal.json: JSDoc of {path}")
            blocks.append((block["line"] - 1, _check_comment_block(block.get("lines"), "jsdoc", python)))
        function_blocks = []
        for block in item.get("function_lens") or []:
            if not isinstance(block, dict) or not isinstance(block.get("line"), int):
                raise ValueError(f"malformed proposal.json: Function Lens id of {path}")
            checked = _check_comment_block(block.get("lines"), "Function Lens id", python)
            match = FUNCTION_LENS_RE.match(checked[0]) if len(checked) == 1 else None
            if match is None or block.get("id") != match.group(1) or not isinstance(block.get("symbol"), str):
                raise ValueError(f"malformed proposal.json: Function Lens id of {path}")
            function_blocks.append((block["line"] - 1, checked))
        draft = Draft(path, str(item.get("group", "")), str(item.get("tag", "")), str(item.get("layer", "")),
                      list(item.get("other_groups") or []), item["sha256"], b"",
                      marker=marker[1] if marker else [], marker_line=marker[0] + 1 if marker else 0)
        raw = _read_inside(root, path)
        if raw is not None and _sha(raw) == draft.sha256:
            text = raw.decode("utf-8")
            lines = split_lines(text.lstrip("﻿"))
            if marker and (marker[0] not in _marker_index(lines, python) or "@featuretrace:" in text):
                raise ValueError(f"malformed proposal.json: the marker of {path} is not where a marker goes")
            if any(not 0 <= index < len(lines) for index, _ in [*blocks, *function_blocks]):
                raise ValueError(f"malformed proposal.json: a symbol documentation line of {path} is outside the file")
            draft.original = raw
            draft.updated = with_blocks(text, marker, blocks, function_blocks).encode("utf-8")
            section = _diff(path, text, draft.updated.decode("utf-8"))
            if section not in sections:
                changed.append((path, "proposal.patch was edited for this file; apply the edited patch with `git apply`"))
                continue
        drafts.append(draft)
    return payload, drafts, changed


def _readme(proposal: Proposal, out_display: str, analysis, settings: FTSettings, owners: bool,
            jsdoc: bool, function_lens: bool, build: str) -> str:
    markers = sum(1 for d in proposal.drafts if d.marker)
    blocks = sum(len(d.jsdoc) for d in proposal.drafts)
    function_ids = sum(len(d.function_lens) for d in proposal.drafts)
    predicted = sum(1 for d in proposal.drafts if d.audit_issues)
    lines = [f"{_README_STAMP}{build} -->", "# FeatureTrace proposal", "",
             f"Drafted by `{GENERATOR}` from static evidence ({build}).", ""]
    reasons = analysis.incomplete_reasons()
    if reasons:
        lines += ["**The analysis was incomplete**, so some files and links may be missing, and `--apply` refuses to run:", ""]
        lines += [f"- {reason}" for reason in reasons] + [""]
    lines += ["| | Count |", "|---|---:|", f"| Files with a drafted marker | {markers} |",
              f"| JSDoc blocks drafted | {blocks} |", f"| Stable Function Lens ids drafted | {function_ids} |",
              f"| Drafts the audit would report issues for | {predicted} |",
              f"| Files left alone | {len(proposal.skipped)} |", ""]
    lines += ["Tags are route segments and roles are drafted from routes, calls and store references. "
              "They say where code is connected, not what the feature is for: rename each tag, rewrite each "
              "role and remove `(draft)` once a person has checked it. A passing `repolens featuretrace audit` "
              "means the references are well formed, not that the declared flow is true.", "",
              "Evidence rules: code a handler reaches follows `exact`, `high` (import-bound) or `declared` calls "
              "only. `Table:`/`Collection:` name stores this file's code (or, for a route file, its handlers) "
              "references, except ambiguous or regex matches and stores only regex matches found; parsed SQL "
              "counts, although no live schema was read. A page or client is "
              "linked to a served route by route-shape matching (`probable`); ambiguous matches are left out, "
              "and `proposal.json` lists each link with its resolution. `Related:` names files with a direct "
              "link, this group's files first and `scripts/`, `migrations/`, `tools/` and vendored code last. "
              "A name-only call links nothing, so a real dependency can be missing.", "",
              "`audit_issues` in `proposal.json` is what `repolens featuretrace audit` would report for each draft "
              "once every draft is applied. The audit reads 20 lines under a marker, so a path in the code under "
              "it (an ES module import) can appear there as a missing reference.", ""]
    if settings.scope_values:
        lines += [f"This repository requires a scope qualifier ({', '.join(settings.scope_values)}); "
                  "add one to each marker before the audit passes.", ""]
    lines += ["## Review and apply", "",
              f"1. Read `{out_display}/proposal.patch`; `proposal.json` lists the evidence behind each block.",
              f"2. `git apply --check {out_display}/proposal.patch`, then `git apply` it, or run "
              f"`{GENERATOR} --apply`. That writes this saved proposal, not a new draft, and skips files that "
              "changed since, are uncommitted or resolve outside the root.",
              "3. To rename tags, draft again with `--tag GROUP=TAG`, review, then apply; then edit the roles.",
              "4. Run `repolens featuretrace audit` and `repolens featuretrace map --index`.", ""]
    if jsdoc:
        lines += ["`--jsdoc` drafts JSDoc only for exported JS/TS route handlers and JS/TS functions that "
                  "reference a store. A JS/TS frontend with no route handlers or data access of its own gets none, "
                  "and Python files never get docstrings.", ""]
    if blocks:
        lines += ["Each JSDoc block starts with `TODO(repolens)`. `repolens docs coverage` counts those symbols as "
                  "undocumented until the line is replaced with what the function is for.", ""]
    if function_lens:
        lines += ["`--function-lens` adds a comment-only `@functionlens:` id to public route, API, data-access "
                  "and exported frontend boundary functions. The id carries no derived call or store claims; "
                  "Function Lens reads it as a stable navigation key, so it can remain with the declaration "
                  "through a rename or move. It has no runtime behavior.", ""]
    if owners:
        lines += [f"`{out_display}/canonical_owners.draft.yaml` is a capability-index draft. It is never written "
                  "into the repository; ownership is a human decision.", ""]
    if proposal.drafts:
        lines += ["## Files", "", "| File | Tag | Layer | Also in | Audit issues |", "|---|---|---|---|---:|"]
        lines += [f"| `{d.path}` | {d.tag} | {d.layer} | {', '.join(d.other_groups) or '-'} | {len(d.audit_issues)} |"
                  for d in proposal.drafts]
        lines.append("")
    if proposal.skipped:
        lines += ["## Left alone", "", "| File | Reason |", "|---|---|"]
        lines += [f"| `{path}` | {reason} |" for path, reason in proposal.skipped]
        lines.append("")
    return "\n".join(lines)


def _apply_saved(root: Path, out: Path, *, allow_dirty: bool) -> int:
    try:
        payload, drafts, edited = load_saved(root, out)
    except ValueError as exc:
        print(f"{GENERATOR} --apply: {exc}")
        return 2
    if not payload.get("complete"):
        print("Refusing --apply: the saved proposal was drafted from an incomplete analysis, so it may miss files or links.")
        return 2
    applied, skipped = apply_drafts(root, drafts, allow_dirty=allow_dirty)
    skipped = sorted([*skipped, *edited])
    for path in applied:
        print(f"  applied  {path}")
    for path, reason in skipped:
        print(f"  skipped  {path}: {reason}")
    if applied:
        print("Next: rename the draft tags and roles, then run `repolens featuretrace audit`.")
    return 1 if skipped else 0


def main(argv: list[str] | None = None, *, config: Config | None = None, prog: str | None = None) -> int:
    """`repolens featuretrace propose`; see the module docstring for exit codes."""
    from ..analysis import analyze
    from ..impact.config import Config as ImpactConfig
    from ..owners.settings import from_config as owner_settings
    from ..provenance import describe_build

    parser = argparse.ArgumentParser(prog=prog, description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out", type=Path, help=f"proposal directory (default {DEFAULT_OUT})")
    parser.add_argument("--apply", action="store_true", help="write the saved proposal into the repository")
    parser.add_argument("--allow-dirty", action="store_true",
                        help="with --apply, also write files git has no clean committed copy of")
    parser.add_argument("--tag", action="append", default=[], metavar="GROUP=TAG", help="name a group's tag")
    parser.add_argument("--only", action="append", default=[], metavar="GROUP", help="draft only these groups")
    parser.add_argument("--jsdoc", action="store_true", help="draft fact-only JSDoc for handlers and data access")
    parser.add_argument("--function-lens", action="store_true",
                        help="draft stable comment-only ids for public feature-boundary functions")
    parser.add_argument("--owners", action="store_true", help="write canonical_owners.draft.yaml to the proposal directory")
    args = parser.parse_args(argv)
    if args.apply and (args.tag or args.only or args.jsdoc or args.function_lens or args.owners):
        parser.error("--apply writes the saved proposal as reviewed; give --tag, --only, --jsdoc, --function-lens and --owners "
                     "to the drafting run instead")
    tags: dict[str, str] = {}
    for item in args.tag:
        group, _, tag = item.partition("=")
        if not group or not _TAG.match(tag):
            parser.error(f"--tag expects GROUP=TAG with a tag of letters, digits, `_`, `.` or `-`: {item!r}")
        tags[group] = tag
    cfg = config or load_config()
    root = cfg.root.resolve()
    out = (args.out if args.out and args.out.is_absolute() else root / (args.out or DEFAULT_OUT)).resolve()
    if out == root:
        parser.error("--out must be a dedicated output directory")
    if not args.out and not out.is_relative_to(root):
        parser.error(f"{DEFAULT_OUT} resolves outside the repository (a symlink); pass --out")
    if args.apply:
        return _apply_saved(root, out, allow_dirty=args.allow_dirty)
    names = ["proposal.patch", "proposal.json", "README.md", *(["canonical_owners.draft.yaml"] if args.owners else [])]
    try:
        _guard_out(out, names)
    except ValueError as exc:
        print(f"{GENERATOR}: {exc}")
        return 2
    impact_settings = ImpactConfig.load(root)
    if out.is_relative_to(root):
        impact_settings.exclude_paths.add(out.relative_to(root).as_posix())
    settings = from_config(cfg)
    try:
        analysis = analyze(root, config=impact_settings)
        proposal = build_proposal(root, analysis.graph, settings, max_file_bytes=impact_settings.max_file_bytes,
                                  tags=tags, only=set(args.only), jsdoc=args.jsdoc,
                                  function_lens=args.function_lens)
    except (OSError, ValueError) as exc:
        print(f"{GENERATOR}: {exc}")
        return 2
    build = describe_build()
    out_display = out.relative_to(root).as_posix() if out.is_relative_to(root) else str(out)
    try:
        out.mkdir(parents=True, exist_ok=True)
        (out / "proposal.patch").write_bytes(_patch(proposal.drafts, build).encode("utf-8"))
        payload = {"generator": GENERATOR, "build": build, "root": root.as_posix(),
                   "complete": analysis.complete, "incomplete_reasons": analysis.incomplete_reasons(),
                   "tags": proposal.tags, "files": [d.to_dict() for d in proposal.drafts],
                   "skipped": [{"path": p, "reason": r} for p, r in proposal.skipped]}
        (out / "proposal.json").write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        (out / "README.md").write_text(_readme(proposal, out_display, analysis, settings, args.owners, args.jsdoc,
                                                args.function_lens, build),
                                       encoding="utf-8")
        if args.owners:
            owners = owners_draft(analysis.graph, proposal.tags, {d.path: d.tag for d in proposal.drafts},
                                  javascript_extensions=tuple(owner_settings(cfg).javascript_extensions))
            (out / "canonical_owners.draft.yaml").write_text(owners, encoding="utf-8")
    except OSError as exc:
        print(f"{GENERATOR}: cannot write the proposal: {exc}")
        return 2
    markers = sum(1 for d in proposal.drafts if d.marker)
    print(f"FeatureTrace proposal: {markers} marker(s), {sum(len(d.jsdoc) for d in proposal.drafts)} JSDoc block(s), "
          f"{sum(len(d.function_lens) for d in proposal.drafts)} Function Lens id(s), "
          f"{len(proposal.skipped)} file(s) left alone; wrote {out_display}")
    for reason in analysis.incomplete_reasons():
        print(f"  incomplete: {reason}")
    if not analysis.complete:
        return 2
    print(f"Review {out_display}/proposal.patch, then run `{GENERATOR} --apply` to write it.")
    return 0
